-- Esquema de Controles Operativos IRJ para Postgres / Supabase.
--
-- Generado desde app/backend/schema.sql. No editar a mano.
-- Pegar entero en el SQL Editor y ejecutar. Es idempotente.

CREATE OR REPLACE FUNCTION datetime(momento text)
RETURNS text LANGUAGE sql STABLE AS $$
    SELECT to_char(
        CASE WHEN momento = 'now' THEN (now() AT TIME ZONE 'UTC')
             ELSE momento::timestamp END,
        'YYYY-MM-DD HH24:MI:SS')
$$;

CREATE OR REPLACE FUNCTION datetime(momento text, modificador text)
RETURNS text LANGUAGE sql STABLE AS $$
    SELECT to_char(
        (CASE WHEN momento = 'now' THEN (now() AT TIME ZONE 'UTC')
              ELSE momento::timestamp END) + modificador::interval,
        'YYYY-MM-DD HH24:MI:SS')
$$;

CREATE TABLE IF NOT EXISTS usuarios (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario       TEXT NOT NULL UNIQUE,
    nombre        TEXT NOT NULL,
    password_hash TEXT NOT NULL,       
    rol           TEXT NOT NULL CHECK (rol IN ('auditor', 'admin')),
    activo        INTEGER NOT NULL DEFAULT 1,
    creado_en     TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS sesiones (
    token      TEXT PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    creado_en  TEXT NOT NULL DEFAULT (datetime('now')),
    ultimo_uso TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS config (
    clave       TEXT PRIMARY KEY,
    valor       TEXT NOT NULL,          
    grupo       TEXT NOT NULL,          
    descripcion TEXT,
    editable    INTEGER NOT NULL DEFAULT 1,
    actualizado TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS sectores_limpieza (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave   TEXT NOT NULL UNIQUE,
    nombre  TEXT NOT NULL,
    orden   INTEGER NOT NULL DEFAULT 0,
    activo  INTEGER NOT NULL DEFAULT 1   
);

CREATE TABLE IF NOT EXISTS items_limpieza (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_id  INTEGER NOT NULL REFERENCES sectores_limpieza(id) ON DELETE CASCADE,
    clave      TEXT NOT NULL,
    nombre     TEXT NOT NULL,
    orden      INTEGER NOT NULL DEFAULT 0,
    activo     INTEGER NOT NULL DEFAULT 1,
    UNIQUE (sector_id, clave)
);

CREATE TABLE IF NOT EXISTS controles_limpieza (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha       TEXT NOT NULL,           
    turno       TEXT NOT NULL DEFAULT 'MANANA'
                CHECK (turno IN ('MANANA', 'TARDE')),
    periodo     TEXT NOT NULL,           
    auditor_id  INTEGER NOT NULL REFERENCES usuarios(id),
    iniciado_en TEXT NOT NULL DEFAULT (datetime('now')),
    cerrado_en  TEXT,
    estado      TEXT NOT NULL DEFAULT 'ABIERTO'
                CHECK (estado IN ('ABIERTO', 'CERRADO')),
    UNIQUE (fecha, turno),
    CHECK (periodo = substr(fecha, 1, 7))
);

CREATE TABLE IF NOT EXISTS control_sectores (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    control_id    INTEGER NOT NULL REFERENCES controles_limpieza(id) ON DELETE CASCADE,
    sector_id     INTEGER NOT NULL REFERENCES sectores_limpieza(id),
    confirmado    INTEGER NOT NULL DEFAULT 0,
    confirmado_en TEXT,
    confirmado_por INTEGER REFERENCES usuarios(id),
    UNIQUE (control_id, sector_id)
);

CREATE TABLE IF NOT EXISTS desvios (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    control_id  INTEGER NOT NULL REFERENCES controles_limpieza(id) ON DELETE CASCADE,
    item_id     INTEGER NOT NULL REFERENCES items_limpieza(id),
    estado      TEXT NOT NULL CHECK (estado IN
                  ('DESVIO_PARCIAL', 'DESVIO_TOTAL', 'NO_VERIFICABLE')),
    observacion TEXT NOT NULL,           
    creado_en   TEXT NOT NULL DEFAULT (datetime('now')),
    creado_por  INTEGER NOT NULL REFERENCES usuarios(id),
    UNIQUE (control_id, item_id)
);

CREATE TABLE IF NOT EXISTS equipamiento_limpieza (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave   TEXT NOT NULL UNIQUE,
    nombre  TEXT NOT NULL,
    exigido INTEGER NOT NULL DEFAULT 1,
    orden   INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS equipamiento_faltante (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    control_id     INTEGER NOT NULL REFERENCES controles_limpieza(id) ON DELETE CASCADE,
    equipamiento_id INTEGER NOT NULL REFERENCES equipamiento_limpieza(id),
    observacion    TEXT,
    registrado_en  TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE (control_id, equipamiento_id)
);

CREATE TABLE IF NOT EXISTS equipamiento_baja (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipamiento_id INTEGER NOT NULL REFERENCES equipamiento_limpieza(id)
                    ON DELETE CASCADE,
    desde           TEXT NOT NULL,          
    hasta           TEXT,                   
    motivo          TEXT NOT NULL,
    control_id      INTEGER REFERENCES controles_limpieza(id) ON DELETE SET NULL,
    registrado_por  INTEGER REFERENCES usuarios(id),
    registrado_en   TEXT NOT NULL DEFAULT (datetime('now')),
    CHECK (hasta IS NULL OR hasta >= desde)
);

CREATE TABLE IF NOT EXISTS periodo_equipamiento (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo         TEXT NOT NULL,
    equipamiento_id INTEGER NOT NULL REFERENCES equipamiento_limpieza(id)
                    ON DELETE CASCADE,
    exigido         INTEGER NOT NULL DEFAULT 1,
    UNIQUE (periodo, equipamiento_id)
);

CREATE TABLE IF NOT EXISTS no_conformidades (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo        TEXT NOT NULL,
    
    
    fecha_origen   TEXT,
    origen         TEXT NOT NULL CHECK (origen IN ('LIMPIEZA', 'LOS')),
    sector         TEXT,
    item           TEXT,
    descripcion    TEXT NOT NULL,
    prioridad      TEXT CHECK (prioridad IN ('PROGRAMADA', 'INMEDIATA')),
    estado         TEXT NOT NULL DEFAULT 'ABIERTA'
                   CHECK (estado IN ('ABIERTA', 'RESUELTA')),
    desvio_id      INTEGER REFERENCES desvios(id) ON DELETE SET NULL,
    creado_en      TEXT NOT NULL DEFAULT (datetime('now')),
    resuelto_en    TEXT,
    resuelto_por   INTEGER REFERENCES usuarios(id),
    resolucion     TEXT                    
);

CREATE TABLE IF NOT EXISTS periodo_datos (
    periodo               TEXT PRIMARY KEY,     
    horas_hombre_programadas  REAL,
    horas_hombre_perdidas     REAL,
    
    
    
    
    documentacion_verificada  INTEGER NOT NULL DEFAULT 0,
    ley_19587_verificada      INTEGER NOT NULL DEFAULT 0,
    -- `hallazgos_*` es bandera, no contador: el PET penaliza el ítem completo
    -- ante un solo hallazgo. El detalle es lo que sostiene esa penalización.
    hallazgos_documentacion   INTEGER NOT NULL DEFAULT 0,
    detalle_hallazgo_documentacion TEXT,
    hallazgos_ley_19587       INTEGER NOT NULL DEFAULT 0,
    detalle_hallazgo_ley_19587     TEXT,
    
    
    
    cerrado                   INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS insumos (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       TEXT NOT NULL UNIQUE,
    punto_pedido REAL NOT NULL DEFAULT 0,
    unidad       TEXT,
    activo       INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS insumo_stock (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo    TEXT NOT NULL,
    insumo_id  INTEGER NOT NULL REFERENCES insumos(id) ON DELETE CASCADE,
    stock      REAL NOT NULL,
    relevado_en TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE (periodo, insumo_id)
);

CREATE TABLE IF NOT EXISTS nucleos_sanitarios (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    tipo   TEXT NOT NULL CHECK (tipo IN
             ('DAMAS', 'CABALLEROS', 'PMR', 'RECINTO_BEBES')),
    ubicacion TEXT,
    activo INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS nucleo_equipos (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nucleo_id  INTEGER NOT NULL REFERENCES nucleos_sanitarios(id) ON DELETE CASCADE,
    equipo     TEXT NOT NULL,          
                                       
    instalados INTEGER NOT NULL DEFAULT 0,
    UNIQUE (nucleo_id, equipo)
);

CREATE TABLE IF NOT EXISTS luminarias_sector (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector    TEXT NOT NULL UNIQUE,
    cantidad  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS puertas_embarque (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     TEXT NOT NULL UNIQUE,
    php        INTEGER NOT NULL DEFAULT 0,   
    instaladas INTEGER NOT NULL DEFAULT 0    
);

CREATE TABLE IF NOT EXISTS medios_elevacion (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      TEXT NOT NULL UNIQUE,
    tipo        TEXT,                        
    redundancia INTEGER NOT NULL DEFAULT 0,
    activo      INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS elevacion_eventos (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_id INTEGER NOT NULL REFERENCES medios_elevacion(id) ON DELETE CASCADE,
    periodo   TEXT NOT NULL,
    inicio    TEXT NOT NULL,
    fin       TEXT,
    horas     REAL,                          
    motivo    TEXT
);

CREATE TABLE IF NOT EXISTS secciones_pavimento (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificador TEXT NOT NULL UNIQUE,
    tipo    TEXT NOT NULL CHECK (tipo IN ('PISTA', 'RODAJE')),
    activo  INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS asientos_preembarque (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id = 1),   
    instalados INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS los_items (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave   TEXT NOT NULL UNIQUE,
    nombre  TEXT NOT NULL,
    orden   INTEGER NOT NULL DEFAULT 0,
    aplica  INTEGER NOT NULL DEFAULT 1,   
    periodicidad TEXT NOT NULL DEFAULT 'MENSUAL'
                 CHECK (periodicidad IN ('DIARIO', 'MENSUAL',
                                         'POR_EVENTO', 'DERIVADO')),
    requiere_inventario TEXT               
);

CREATE TABLE IF NOT EXISTS relevamientos_los (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo    TEXT NOT NULL,
    fecha      TEXT NOT NULL DEFAULT (datetime('now')),
    auditor_id INTEGER NOT NULL REFERENCES usuarios(id),
    estado     TEXT NOT NULL DEFAULT 'ABIERTO'
               CHECK (estado IN ('ABIERTO', 'CERRADO')),
    cerrado_en TEXT
);

CREATE TABLE IF NOT EXISTS los_mediciones (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relevamiento_id INTEGER NOT NULL REFERENCES relevamientos_los(id) ON DELETE CASCADE,
    item_clave      TEXT NOT NULL REFERENCES los_items(clave),
    fecha           TEXT NOT NULL DEFAULT '',   
    datos           TEXT NOT NULL,       
    resultado       TEXT,                
    cumple          INTEGER,             
    observaciones   TEXT,
    creado_en       TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE (relevamiento_id, item_clave, fecha)
);

CREATE TABLE IF NOT EXISTS fotos (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad     TEXT NOT NULL,           
    entidad_id  INTEGER NOT NULL,
    
    
    
    subitem     TEXT,
    archivo     TEXT NOT NULL,           
    tomada_en   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS firmas (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad     TEXT NOT NULL,           
    entidad_id  INTEGER NOT NULL,
    rol_firmante TEXT NOT NULL,          
    nombre      TEXT NOT NULL,
    trazo       TEXT NOT NULL,           
    firmado_en  TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS auditoria_log (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER REFERENCES usuarios(id),
    accion     TEXT NOT NULL,
    entidad    TEXT,
    entidad_id INTEGER,
    detalle    TEXT,
    fecha      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS sync_operaciones (
    uuid        TEXT PRIMARY KEY,
    recibido_en TEXT NOT NULL DEFAULT (datetime('now')),
    resultado   TEXT
);

CREATE TABLE IF NOT EXISTS intentos_login (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave   TEXT NOT NULL,          
    momento TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_intentos_login   ON intentos_login(clave, momento);

CREATE INDEX IF NOT EXISTS idx_controles_periodo ON controles_limpieza(periodo);

CREATE INDEX IF NOT EXISTS idx_desvios_control  ON desvios(control_id);

CREATE INDEX IF NOT EXISTS idx_items_sector     ON items_limpieza(sector_id);

CREATE INDEX IF NOT EXISTS idx_nc_periodo       ON no_conformidades(periodo, estado);

CREATE INDEX IF NOT EXISTS idx_los_med_relev    ON los_mediciones(relevamiento_id);

CREATE INDEX IF NOT EXISTS idx_fotos_entidad    ON fotos(entidad, entidad_id);

CREATE INDEX IF NOT EXISTS idx_elev_periodo     ON elevacion_eventos(periodo);

CREATE INDEX IF NOT EXISTS idx_equip_baja       ON equipamiento_baja(equipamiento_id, desde);

CREATE TABLE IF NOT EXISTS artefacto_baja (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nucleo_id   INTEGER NOT NULL REFERENCES nucleos_sanitarios(id) ON DELETE CASCADE,
    equipo      TEXT NOT NULL,          
    cantidad    INTEGER NOT NULL DEFAULT 1,
    desde       TEXT NOT NULL,          
    hasta       TEXT,                   
    motivo      TEXT NOT NULL,
    control_id  INTEGER REFERENCES controles_limpieza(id) ON DELETE SET NULL,
    registrado_por INTEGER REFERENCES usuarios(id),
    registrado_en  TEXT NOT NULL DEFAULT (datetime('now')),
    CHECK (cantidad > 0),
    CHECK (hasta IS NULL OR hasta >= desde)
);

CREATE INDEX IF NOT EXISTS idx_artefacto_baja   ON artefacto_baja(nucleo_id, desde);

