"""Capa de compatibilidad para correr el mismo código sobre SQLite o Postgres.

Estrategia: en vez de traducir a mano las 139 consultas de `services.py` e
`informes.py` —que es donde se calculan los importes a certificar y donde un
error se paga caro—, se hace que Postgres acepte el SQL que ya está escrito y
que los 540 tests ya cubren.

Tres piezas:

1. Reescritura mecánica de lo poco que Postgres no entiende: los placeholders
   `?` y `INSERT OR IGNORE`.
2. Una función SQL propia, `datetime()`, que replica la de SQLite, para no
   tocar las 32 apariciones repartidas entre el esquema y el código.
3. Un envoltorio de conexión (en `db.py`) que imita la API de `sqlite3` que usa
   el resto del backend.

Decisión deliberada: las marcas de tiempo siguen siendo TEXT, no `timestamp`.
La aplicación las compara como cadenas (`s.ultimo_uso >= datetime('now', ?)`),
deriva el período con `substr(fecha, 1, 7)` y ordena por texto. Migrarlas a
tipos nativos obligaría a revisar cada una de esas comparaciones; mantenerlas
como texto conserva la semántica exacta y deja los tests como red de seguridad.
"""

from __future__ import annotations

import re

# Formato exacto de `datetime('now')` en SQLite: 'AAAA-MM-DD HH:MM:SS' en UTC.
FORMATO_SQLITE = "YYYY-MM-DD HH24:MI:SS"

# `datetime()` no existe en Postgres y el SQL de la app la da por sentada.
#
# La versión de un argumento acepta 'now' o una marca ya formada. La de dos
# aplica un modificador estilo SQLite ('-30 days'), que es como la app calcula
# el vencimiento de las sesiones. No se define `date()`: ese nombre colisiona
# con el tipo homónimo de Postgres, y su único uso en SQL está dentro de
# `migrar()`, que solo corre sobre SQLite.
FUNCIONES_SQL = f"""
CREATE OR REPLACE FUNCTION datetime(momento text)
RETURNS text LANGUAGE sql STABLE AS $$
    SELECT to_char(
        CASE WHEN momento = 'now' THEN (now() AT TIME ZONE 'UTC')
             ELSE momento::timestamp END,
        '{FORMATO_SQLITE}')
$$;

CREATE OR REPLACE FUNCTION datetime(momento text, modificador text)
RETURNS text LANGUAGE sql STABLE AS $$
    SELECT to_char(
        (CASE WHEN momento = 'now' THEN (now() AT TIME ZONE 'UTC')
              ELSE momento::timestamp END) + modificador::interval,
        '{FORMATO_SQLITE}')
$$;
"""


def traducir_esquema(ddl: str) -> str:
    """Convierte el DDL de `schema.sql` al dialecto de Postgres.

    Se traduce en tiempo de ejecución en vez de mantener un segundo archivo:
    dos esquemas separados se desincronizan a la primera columna que alguien
    agregue en uno y olvide en el otro, y acá eso significaría que la base de
    producción y la de los tests dejan de ser la misma.

    Solo hacen falta dos reglas. El esquema no usa triggers, vistas,
    `WITHOUT ROWID`, `AUTOINCREMENT` ni collations, y los tipos TEXT, INTEGER y
    REAL existen igual en Postgres. Las columnas booleanas siguen siendo
    INTEGER a propósito, para que las comparaciones `activo = 1` que hay
    repartidas por el código sigan valiendo.
    """
    # Las PRAGMA no existen: en Postgres las claves foráneas siempre rigen.
    ddl = re.sub(r"^\s*PRAGMA[^;]*;\s*$", "", ddl, flags=re.IGNORECASE | re.MULTILINE)

    # En SQLite `INTEGER PRIMARY KEY` es alias del rowid y se autoincrementa.
    # BY DEFAULT, no ALWAYS: hay tablas que insertan el id explícito (la fila
    # única de asientos_preembarque lleva CHECK (id = 1)).
    ddl = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY",
                 "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                 ddl, flags=re.IGNORECASE)
    return ddl


def sentencias(ddl: str) -> list[str]:
    """Parte un script en sentencias, respetando literales y comentarios."""
    partes, actual = [], []
    en_texto = False
    i = 0
    while i < len(ddl):
        c = ddl[i]
        if not en_texto and ddl.startswith("--", i):
            fin = ddl.find("\n", i)
            i = len(ddl) if fin == -1 else fin
            continue
        if c == "'":
            en_texto = not en_texto
        if c == ";" and not en_texto:
            partes.append("".join(actual))
            actual = []
        else:
            actual.append(c)
        i += 1
    partes.append("".join(actual))
    return [p.strip() for p in partes if p.strip()]


def traducir(sql: str, con_parametros: bool) -> str:
    """Adapta al dialecto de Postgres el SQL escrito para SQLite.

    con_parametros: si la consulta lleva valores. psycopg solo interpreta `%`
    cuando los hay, así que escaparlos siempre dejaría `%%` literales en las
    consultas sin parámetros.
    """
    if re.search(r"INSERT\s+OR\s+IGNORE\s+INTO", sql, re.IGNORECASE):
        # Traducción directa: las dos formas descartan la fila que viola una
        # restricción de unicidad en lugar de fallar.
        sql = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", sql,
                     flags=re.IGNORECASE)
        if not re.search(r"ON\s+CONFLICT", sql, re.IGNORECASE):
            sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"

    return _placeholders(sql) if con_parametros else sql


def _placeholders(sql: str) -> str:
    """Cambia `?` por `%s`, sin tocar los que viven dentro de comillas simples.

    El esquema tiene literales con texto en los CHECK, así que no alcanza con
    un reemplazo global.
    """
    salida = []
    en_texto = False
    i = 0
    while i < len(sql):
        c = sql[i]
        if c == "'":
            # '' escapado dentro de un literal: no abre ni cierra.
            if en_texto and i + 1 < len(sql) and sql[i + 1] == "'":
                salida.append("''")
                i += 2
                continue
            en_texto = not en_texto
            salida.append(c)
        elif c == "?" and not en_texto:
            salida.append("%s")
        elif c == "%":
            # psycopg consume los % al interpolar: hay que duplicarlos para que
            # lleguen literales a la base.
            salida.append("%%")
        else:
            salida.append(c)
        i += 1
    return "".join(salida)
